local M = {
  events = {
    WORKSPACE_OPEN_REQUESTED = "WORKSPACE_OPEN_REQUESTED",
    WORKSPACE_CLOSE_REQUESTED = "WORKSPACE_CLOSE_REQUESTED",
    WORKSPACE_TOGGLE_REQUESTED = "WORKSPACE_TOGGLE_REQUESTED",

    TERMINAL_CREATE_REQUESTED = "TERMINAL_CREATE_REQUESTED",
    TERMINAL_DELETE_REQUESTED = "TERMINAL_DELETE_REQUESTED",
    TERMINAL_RENAME_REQUESTED = "TERMINAL_RENAME_REQUESTED",
    TERMINAL_SELECT_REQUESTED = "TERMINAL_SELECT_REQUESTED",
    TERMINAL_READ_REQUESTED = "TERMINAL_READ_REQUESTED",
    TERMINAL_NEXT_REQUESTED = "TERMINAL_NEXT_REQUESTED",
    TERMINAL_PREV_REQUESTED = "TERMINAL_PREV_REQUESTED",
    TERMINAL_MOVE_REQUESTED = "TERMINAL_MOVE_REQUESTED",
    TERMINAL_START_REQUESTED = "TERMINAL_START_REQUESTED",
    TERMINAL_START_FAILED = "TERMINAL_START_FAILED",

    TERMINAL_PROCESS_OPENED = "TERMINAL_PROCESS_OPENED",
    TERMINAL_PROCESS_EXITED = "TERMINAL_PROCESS_EXITED",

    SHELL_INTEGRATION_DETECTED = "SHELL_INTEGRATION_DETECTED",
    SHELL_PROMPT_STARTED = "SHELL_PROMPT_STARTED",
    SHELL_COMMAND_INPUT_STARTED = "SHELL_COMMAND_INPUT_STARTED",
    SHELL_COMMAND_EXECUTED = "SHELL_COMMAND_EXECUTED",
    SHELL_COMMAND_FINISHED = "SHELL_COMMAND_FINISHED",
    SHELL_COMMAND_ABORTED = "SHELL_COMMAND_ABORTED",

    TERMINAL_CWD_REPORTED = "TERMINAL_CWD_REPORTED",
    TERMINAL_TITLE_UPDATED = "TERMINAL_TITLE_UPDATED",
    SHELL_BACKGROUND_JOB_NOTIFIED = "SHELL_BACKGROUND_JOB_NOTIFIED",

    TABPAGE_CLOSED = "TABPAGE_CLOSED",
    TERMINAL_BUFFER_WIPED_EXTERNALLY = "TERMINAL_BUFFER_WIPED_EXTERNALLY",
    SIDEBAR_WINDOW_CLOSED_EXTERNALLY = "SIDEBAR_WINDOW_CLOSED_EXTERNALLY",
    PANEL_WINDOW_CLOSED_EXTERNALLY = "PANEL_WINDOW_CLOSED_EXTERNALLY",
  },

  ui_commands = {
    MOUNT = "MOUNT",
    UNMOUNT = "UNMOUNT",
    RELAYOUT = "RELAYOUT",
    RENDER_SIDEBAR = "RENDER_SIDEBAR",
    RENDER_PLACEHOLDER = "RENDER_PLACEHOLDER",
    START_TERMINAL = "START_TERMINAL",
    MOUNT_TERMINAL = "MOUNT_TERMINAL",
    DISPOSE_TERMINAL_BUFFERS = "DISPOSE_TERMINAL_BUFFERS",
  },
}

return M
