import { normalizePermissionPolicy } from "./policy.ts";
import type { AgentDefinition, PermissionPolicy } from "./types.ts";

function permission(value: unknown): PermissionPolicy {
  return normalizePermissionPolicy(value) ?? {};
}

const protectedReadToolRules: Record<string, "allow" | "deny"> = {
  "*": "allow",
  ".git": "deny",
  ".git/**": "deny",
  "secrets": "deny",
  "secrets/**": "deny",
  ".env": "deny",
  ".env.*": "deny",
  ".env.example": "allow",
  "**/.env": "deny",
  "**/.env.*": "deny",
  "**/.env.example": "allow",
};

const protectedMutationToolRules: Record<string, "allow" | "deny"> = {
  "*": "allow",
  ".git": "deny",
  ".git/**": "deny",
  "secrets": "deny",
  "secrets/**": "deny",
  ".env": "deny",
  ".env.*": "deny",
  "**/.env": "deny",
  "**/.env.*": "deny",
  "/nix/store": "deny",
  "/nix/store/**": "deny",
};

const safeInspectionBashRules: Record<string, "allow" | "deny"> = {
  "*": "deny",
  "cat *": "allow",
  "head *": "allow",
  "tail *": "allow",
  "less *": "allow",
  "more *": "allow",
  "grep *": "allow",
  "rg *": "allow",
  "find *": "allow",
  "fd *": "allow",
  "ls*": "allow",
  "pwd": "allow",
  "echo *": "allow",
  "printf *": "allow",
  "wc *": "allow",
  "sort *": "allow",
  "uniq *": "allow",
  "diff *": "allow",
  "file *": "allow",
  "stat *": "allow",
  "du *": "allow",
  "df *": "allow",
  "tree *": "allow",
  "which *": "allow",
  "whereis *": "allow",
  "type *": "allow",
  "env": "allow",
  "printenv*": "allow",
  "uname*": "allow",
  "whoami": "allow",
  "id": "allow",
  "date": "allow",
  "ps*": "allow",
  "jq *": "allow",
  "bat *": "allow",
  "eza *": "allow",
  "git status*": "allow",
  "git log*": "allow",
  "git diff*": "allow",
  "git show*": "allow",
  "git branch*": "allow",
  "git remote*": "allow",
  "git config --get*": "allow",
  "git ls-*": "allow",
  "npm list*": "allow",
  "npm ls*": "allow",
  "npm view*": "allow",
  "npm info*": "allow",
  "npm search*": "allow",
  "npm outdated*": "allow",
  "npm audit*": "allow",
  "node --version*": "allow",
  "python --version*": "allow",
  "rm *": "deny",
  "sudo *": "deny",
  "chmod *": "deny",
  "chown *": "deny",
  "*>*": "deny",
};

export const builtinAgents: AgentDefinition[] = [
  {
    name: "plan",
    kind: "main",
    source: "builtin",
    description: "Read-only exploration and implementation planning agent.",
    enabled: true,
    promptMode: "append",
    thinking: "xhigh",
    prompt: [
      "You are the plan main agent.",
      "Explore and reason carefully, but do not mutate files or system state.",
      "Use subagents only when their delegated policy allows it.",
      "Produce concise plans, risks, and verification steps.",
    ].join("\n"),
    permission: permission({
      "*": "allow",
      tools: {
        "*": "allow",
        read: protectedReadToolRules,
        grep: protectedReadToolRules,
        find: protectedReadToolRules,
        ls: protectedReadToolRules,
        bash: "allow",
        subagent: "ask",
        get_subagent_result: "allow",
        steer_subagent: "ask",
        edit: "deny",
        write: "deny",
      },
      bash: safeInspectionBashRules,
      external_directory: {
        "*": "ask",
        "/nix/store/**": "allow",
      },
      subagents: {
        "*": "ask",
        scout: "allow",
        "docs-digger": "allow",
        "source:project": "ask",
        "override:model": "ask",
      },
    }),
  },
  {
    name: "build",
    kind: "main",
    source: "builtin",
    description: "Implementation agent with approval gates for mutations and commands.",
    enabled: true,
    promptMode: "append",
    thinking: "xhigh",
    prompt: [
      "You are the build main agent.",
      "Make focused implementation changes and use permission prompts for risky actions.",
      "Keep scope tight and preserve unrelated user work.",
    ].join("\n"),
    permission: permission({
      "*": "ask",
      tools: {
        "*": "allow",
        read: protectedReadToolRules,
        edit: protectedMutationToolRules,
        write: protectedMutationToolRules,
      },
      bash: {
        "*": "allow",
        "*rm -rf*": "deny",
        "*sudo*": "deny",
        "git reset --hard*": "deny",
      },
      external_directory: {
        "*": "ask",
        "/nix/store/**": "allow",
      },
      subagents: {
        "*": "ask",
        scout: "allow",
        "docs-digger": "allow",
        codemodder: "ask",
        "source:project": "ask",
        "override:model": "ask",
      },
    }),
  },
  {
    name: "ask",
    kind: "main",
    source: "builtin",
    description: "Conversational and research agent with minimal local mutation access.",
    enabled: true,
    promptMode: "append",
    thinking: "medium",
    prompt: [
      "You are the ask main agent.",
      "Answer questions, research, and clarify requirements.",
      "Avoid mutating files or executing shell commands unless explicitly approved.",
    ].join("\n"),
    permission: permission({
      "*": "ask",
      tools: {
        "*": "allow",
        read: protectedReadToolRules,
        grep: protectedReadToolRules,
        find: protectedReadToolRules,
        ls: protectedReadToolRules,
        subagent: "ask",
        get_subagent_result: "allow",
        bash: "deny",
        edit: "deny",
        write: "deny",
      },
      external_directory: {
        "*": "ask",
        "/nix/store/**": "allow",
      },
      subagents: {
        "*": "ask",
        scout: "allow",
        "docs-digger": "allow",
        "source:project": "ask",
      },
    }),
  },
];
