# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@anthropic-ai/tokenizer@0.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@anthropic-ai/tokenizer/-/tokenizer-0.0.4.tgz";
    hash = "sha512-EHRKbxlxlc8W4KCBEseByJ7YwyYCmgu9OyN59H9+IYIGPoKv8tXyQXinkeGDI+cI8Tiuz9wk2jZb/kK7AyvL7g==";
  };
  "@babel/generator@7.28.5" = fetchurl {
    url = "https://registry.npmjs.org/@babel/generator/-/generator-7.28.5.tgz";
    hash = "sha512-3EwLFhZ38J4VyIP6WNtt2kUdW9dokXA9Cr4IVIFHuCpZ3H8/YFOl5JjZHisrn1fATPBmKKqXzDFvh9fUwHz6CQ==";
  };
  "@babel/helper-string-parser@7.27.1" = fetchurl {
    url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.27.1.tgz";
    hash = "sha512-qMlSxKbpRlAridDExk92nSobyDdpPijUq2DW6oDnUqd0iOGxmQjyqhMIihI9+zv4LPyZdRje2cavWPbCbWm3eA==";
  };
  "@babel/helper-validator-identifier@7.28.5" = fetchurl {
    url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz";
    hash = "sha512-qSs4ifwzKJSV39ucNjsvc6WVHs6b7S03sOh2OcHF9UHfVPqWWALUsNUVzhSBiItjRZoLHx7nIarVjqKVusUZ1Q==";
  };
  "@babel/parser@7.28.5" = fetchurl {
    url = "https://registry.npmjs.org/@babel/parser/-/parser-7.28.5.tgz";
    hash = "sha512-KKBU1VGYR7ORr3At5HAtUQ+TV3SzRCXmA/8OdDZiLDBIZxVyzXuztPjfLd3BV1PRAQGCMWWSHYhL0F8d5uHBDQ==";
  };
  "@babel/types@7.28.5" = fetchurl {
    url = "https://registry.npmjs.org/@babel/types/-/types-7.28.5.tgz";
    hash = "sha512-qQ5m48eI/MFLQ5PxQj4PFaprjyCTLI37ElWMmNs0K8Lk3dVeOdNpB3ks8jc7yM5CDmVC73eMVk/trk3fgmrUpA==";
  };
  "@bufbuild/protobuf@1.10.0" = fetchurl {
    url = "https://registry.npmjs.org/@bufbuild/protobuf/-/protobuf-1.10.0.tgz";
    hash = "sha512-QDdVFLoN93Zjg36NoQPZfsVH9tZew7wKDKyV5qRdj8ntT4wQCOradQjRaTdwMhWUYsgKsvCINKKm87FdEk96Ag==";
  };
  "@hey-api/json-schema-ref-parser@1.0.6" = fetchurl {
    url = "https://registry.npmjs.org/@hey-api/json-schema-ref-parser/-/json-schema-ref-parser-1.0.6.tgz";
    hash = "sha512-yktiFZoWPtEW8QKS65eqKwA5MTKp88CyiL8q72WynrBs/73SAaxlSWlA2zW/DZlywZ5hX1OYzrCC0wFdvO9c2w==";
  };
  "@hey-api/openapi-ts@0.81.0" = fetchurl {
    url = "https://registry.npmjs.org/@hey-api/openapi-ts/-/openapi-ts-0.81.0.tgz";
    hash = "sha512-PoJukNBkUfHOoMDpN33bBETX49TUhy7Hu8Sa0jslOvFndvZ5VjQr4Nl/Dzjb9LG1Lp5HjybyTJMA6a1zYk/q6A==";
  };
  "@jridgewell/gen-mapping@0.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
    hash = "sha512-2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
  };
  "@jridgewell/resolve-uri@3.1.2" = fetchurl {
    url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
    hash = "sha512-bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
  };
  "@jridgewell/sourcemap-codec@1.5.5" = fetchurl {
    url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
    hash = "sha512-cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
  };
  "@jridgewell/trace-mapping@0.3.31" = fetchurl {
    url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
    hash = "sha512-zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
  };
  "@jsdevtools/ono@7.1.3" = fetchurl {
    url = "https://registry.npmjs.org/@jsdevtools/ono/-/ono-7.1.3.tgz";
    hash = "sha512-4JQNk+3mVzK3xh2rqd6RB4J46qUR19azEHBneZyTZM+c456qOrbbM/5xcR8huNCCcbVt7+UmizG6GuUvPvKUYg==";
  };
  "@opencode-ai/plugin@0.13.9" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/plugin/-/plugin-0.13.9.tgz";
    hash = "sha512-1wZo36HORH6GTMcQXGAkm/J426e1WS2JKrjPZYoT9vHMnrKPfNHnMprruYs0q7//6j8liZNAN4C1XzdkkFA0eQ==";
  };
  "@opencode-ai/sdk@0.13.9" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/sdk/-/sdk-0.13.9.tgz";
    hash = "sha512-McMRieAokJJeNT9QUBmDWIJOyuiXN8KusziBYhHp+K+Lxp/MKv0iIEhVEibTsRyL+NuMc14epLn9whwuZYpRkA==";
  };
  "@types/babel__generator@7.27.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/babel__generator/-/babel__generator-7.27.0.tgz";
    hash = "sha512-ufFd2Xi92OAVPYsy+P4n7/U7e68fex0+Ee8gSG9KX7eo084CWiQ4sdxktvdl0bOPupXtVJPY19zk6EwWqUQ8lg==";
  };
  "@types/bun@1.3.3" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.3.tgz";
    hash = "sha512-ogrKbJ2X5N0kWLLFKeytG0eHDleBYtngtlbu9cyBKFtNL3cnpDZkNdQj8flVf6WTZUX5ulI9AY1oa7ljhSrp+g==";
  };
  "@types/json-schema@7.0.15" = fetchurl {
    url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.15.tgz";
    hash = "sha512-5+fP8P8MFNC+AyZCDxrB2pkZFPGzqQWUzpSeuuVLvm8VMcorNYavBqoFcxK8bQz4Qsbn4oUEEem4wDLfcysGHA==";
  };
  "@types/node@18.19.130" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-18.19.130.tgz";
    hash = "sha512-GRaXQx6jGfL8sKfaIDD6OupbIHBr9jv7Jnaml9tB7l4v068PAOXqfcujMMo5PhbIs6ggR1XODELqahT2R8v0fg==";
  };
  "@types/node@24.10.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-24.10.1.tgz";
    hash = "sha512-GNWcUTRBgIRJD5zj+Tq0fKOJ5XZajIiBroOF0yvj2bSU1WvNdYS/dn9UxwsujGW4JX06dnHyjV2y9rRaybH0iQ==";
  };
  "acorn@8.15.0" = fetchurl {
    url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
    hash = "sha512-NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
  };
  "ansi-colors@4.1.3" = fetchurl {
    url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.3.tgz";
    hash = "sha512-/6w/C21Pm1A7aZitlI5Ni/2J6FFQN8i1Cvz3kHABAAbw93v/NlvKdVOqz7CCWz/3iv/JplRSEEZ83XION15ovw==";
  };
  "argparse@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
    hash = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
  };
  "bun-types@1.3.3" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.3.tgz";
    hash = "sha512-z3Xwlg7j2l9JY27x5Qn3Wlyos8YAp0kKRlrePAOjgjMGS5IG6E7Jnlx736vH9UVI4wUICwwhC9anYL++XeOgTQ==";
  };
  "bundle-name@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/bundle-name/-/bundle-name-4.1.0.tgz";
    hash = "sha512-tjwM5exMg6BGRI+kNmTntNsvdZS1X8BFYS6tnJ2hdH0kVxM6/eVZ2xy+FqStSWvYmtfFMDLIxurorHwDKfDz5Q==";
  };
  "c12@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/c12/-/c12-2.0.1.tgz";
    hash = "sha512-Z4JgsKXHG37C6PYUtIxCfLJZvo6FyhHJoClwwb9ftUkLpPSkuYqn6Tr+vnaN8hymm0kIbcg6Ey3kv/Q71k5w/A==";
  };
  "chokidar@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/chokidar/-/chokidar-4.0.3.tgz";
    hash = "sha512-Qgzu8kfBvo+cA4962jnP1KkS6Dop5NS6g7R5LFYJr4b8Ub94PPQXUksCw9PvXoeXPRRddRNC5C1JQUR2SMGtnA==";
  };
  "chownr@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/chownr/-/chownr-2.0.0.tgz";
    hash = "sha512-bIomtDF5KGpdogkLd9VspvFzk9KfpyyGlS8YFVZl7TGPBHL5snIOnxeshwVgPteQ9b4Eydl+pVbIyE1DcvCWgQ==";
  };
  "citty@0.1.6" = fetchurl {
    url = "https://registry.npmjs.org/citty/-/citty-0.1.6.tgz";
    hash = "sha512-tskPPKEs8D2KPafUypv2gxwJP8h/OaJmC82QQGGDQcHvXX43xF2VDACcJVmZ0EuSxkpO9Kc4MlrA3q0+FG58AQ==";
  };
  "color-support@1.1.3" = fetchurl {
    url = "https://registry.npmjs.org/color-support/-/color-support-1.1.3.tgz";
    hash = "sha512-qiBjkpbMLO/HL68y+lh4q0/O1MZFj2RX6X/KmMa3+gJD3z+WwI1ZzDHysvqHGS3mP6mznPckpXmw1nI9cJjyRg==";
  };
  "commander@13.0.0" = fetchurl {
    url = "https://registry.npmjs.org/commander/-/commander-13.0.0.tgz";
    hash = "sha512-oPYleIY8wmTVzkvQq10AEok6YcTC4sRUBl8F9gVuwchGVUCTbl/vhLTaQqutuuySYOsu8YTgV+OxKc/8Yvx+mQ==";
  };
  "confbox@0.1.8" = fetchurl {
    url = "https://registry.npmjs.org/confbox/-/confbox-0.1.8.tgz";
    hash = "sha512-RMtmw0iFkeR4YV+fUOSucriAQNb9g8zFR52MWCtl+cCZOFRNL6zeB395vPzFhEjjn4fMxXudmELnl/KF/WrK6w==";
  };
  "consola@3.4.2" = fetchurl {
    url = "https://registry.npmjs.org/consola/-/consola-3.4.2.tgz";
    hash = "sha512-5IKcdX0nnYavi6G7TtOhwkYzyjfJlatbjMjuLSfE2kYT5pMDOilZ4OvMhi637CcDICTmz3wARPoyhqyX1Y+XvA==";
  };
  "default-browser-id@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/default-browser-id/-/default-browser-id-5.0.1.tgz";
    hash = "sha512-x1VCxdX4t+8wVfd1so/9w+vQ4vx7lKd2Qp5tDRutErwmR85OgmfX7RlLRMWafRMY7hbEiXIbudNrjOAPa/hL8Q==";
  };
  "default-browser@5.4.0" = fetchurl {
    url = "https://registry.npmjs.org/default-browser/-/default-browser-5.4.0.tgz";
    hash = "sha512-XDuvSq38Hr1MdN47EDvYtx3U0MTqpCEn+F6ft8z2vYDzMrvQhVp0ui9oQdqW3MvK3vqUETglt1tVGgjLuJ5izg==";
  };
  "define-lazy-prop@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-3.0.0.tgz";
    hash = "sha512-N+MeXYoqr3pOgn8xfyRPREN7gHakLYjhsHhWGT3fWAiL4IkAt0iDw14QiiEm2bE30c5XX5q0FtAA3CK5f9/BUg==";
  };
  "defu@6.1.4" = fetchurl {
    url = "https://registry.npmjs.org/defu/-/defu-6.1.4.tgz";
    hash = "sha512-mEQCMmwJu317oSz8CwdIOdwf3xMif1ttiM8LTufzc3g6kR+9Pe236twL8j3IYT1F7GfRgGcW6MWxzZjLIkuHIg==";
  };
  "destr@2.0.5" = fetchurl {
    url = "https://registry.npmjs.org/destr/-/destr-2.0.5.tgz";
    hash = "sha512-ugFTXCtDZunbzasqBxrK93Ik/DRYsO6S/fedkWEMKqt04xZ4csmnmwGDBAb07QWNaGMAmnTIemsYZCksjATwsA==";
  };
  "dotenv@16.6.1" = fetchurl {
    url = "https://registry.npmjs.org/dotenv/-/dotenv-16.6.1.tgz";
    hash = "sha512-uBq4egWHTcTt33a72vpSG0z3HnPuIl6NqYcTrKEg2azoEyl2hpW0zqlxysq2pK9HlDIHyHyakeYaYnSAwd8bow==";
  };
  "fs-minipass@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-2.1.0.tgz";
    hash = "sha512-V/JgOLFCS+R6Vcq0slCuaeWEdNC3ouDlJMNIsacH2VtALiu9mV4LPrHc5cDl8k5aw6J8jwgWWpiTo5RYhmIzvg==";
  };
  "giget@1.2.5" = fetchurl {
    url = "https://registry.npmjs.org/giget/-/giget-1.2.5.tgz";
    hash = "sha512-r1ekGw/Bgpi3HLV3h1MRBIlSAdHoIMklpaQ3OQLFcRw9PwAj2rqigvIbg+dBUI51OxVI2jsEtDywDBjSiuf7Ug==";
  };
  "gpt-tokenizer@3.4.0" = fetchurl {
    url = "https://registry.npmjs.org/gpt-tokenizer/-/gpt-tokenizer-3.4.0.tgz";
    hash = "sha512-wxFLnhIXTDjYebd9A9pGl3e31ZpSypbpIJSOswbgop5jLte/AsZVDvjlbEuVFlsqZixVKqbcoNmRlFDf6pz/UQ==";
  };
  "handlebars@4.7.8" = fetchurl {
    url = "https://registry.npmjs.org/handlebars/-/handlebars-4.7.8.tgz";
    hash = "sha512-vafaFqs8MZkRrSX7sFVUdo3ap/eNiLnb4IakshzvP56X5Nr1iGKAIqdX6tMlm6HcNRIkr6AxO5jFEoJzzpT8aQ==";
  };
  "is-docker@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-docker/-/is-docker-3.0.0.tgz";
    hash = "sha512-eljcgEDlEns/7AXFosB5K/2nCM4P7FQPkGc/DWLy5rmFEWvZayGrik1d9/QIY5nJ4f9YsVvBkA6kJpHn9rISdQ==";
  };
  "is-inside-container@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-inside-container/-/is-inside-container-1.0.0.tgz";
    hash = "sha512-KIYLCCJghfHZxqjYBE7rEy0OBuTd5xCHS7tHVgvCLkx7StIoaxwNW3hCALgEUjFfeRk+MG/Qxmp/vtETEF3tRA==";
  };
  "is-wsl@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-wsl/-/is-wsl-3.1.0.tgz";
    hash = "sha512-UcVfVfaK4Sc4m7X3dUSoHoozQGBEFeDC+zVo06t98xe8CzHSZZBekNXH+tu0NalHolcJ/QAGqS46Hef7QXBIMw==";
  };
  "jiti@2.6.1" = fetchurl {
    url = "https://registry.npmjs.org/jiti/-/jiti-2.6.1.tgz";
    hash = "sha512-ekilCSN1jwRvIbgeg/57YFh8qQDNbwDb9xT/qu2DAHbFFZUicIl4ygVaAvzveMhMVr3LnpSKTNnwt8PoOfmKhQ==";
  };
  "js-yaml@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz";
    hash = "sha512-wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==";
  };
  "jsesc@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/jsesc/-/jsesc-3.1.0.tgz";
    hash = "sha512-/sM3dO2FOzXjKQhJuo0Q173wf2KOo8t4I8vHy6lF9poUp7bKT0/NHE8fPX23PwfhnykfqnC2xRxOnVw5XuGIaA==";
  };
  "llm-info@1.0.69" = fetchurl {
    url = "https://registry.npmjs.org/llm-info/-/llm-info-1.0.69.tgz";
    hash = "sha512-5AaEwzjVfAHGQKLrt5+/9d8SMm517U3qvO0pC5lZB3QMto5T7NQs9xVG+XRW25ZTiZ2udDSrwWRosq/Qu4I0Ng==";
  };
  "lodash@4.17.21" = fetchurl {
    url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
    hash = "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
  };
  "minimist@1.2.8" = fetchurl {
    url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
    hash = "sha512-2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
  };
  "minipass@3.3.6" = fetchurl {
    url = "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz";
    hash = "sha512-DxiNidxSEK+tHG6zOIklvNOwm3hvCrbUrdtzY74U6HKTJxvIDfOUL5W5P2Ghd3DTkhhKPYGqeNUIh5qcM4YBfw==";
  };
  "minipass@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/minipass/-/minipass-5.0.0.tgz";
    hash = "sha512-3FnjYuehv9k6ovOEbyOswadCDPX1piCfhV8ncmYtHOjuPwylVWsghTLo7rabjC3Rx5xD4HDx8Wm1xnMF7S5qFQ==";
  };
  "minizlib@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/minizlib/-/minizlib-2.1.2.tgz";
    hash = "sha512-bAxsR8BVfj60DWXHE3u30oHzfl4G7khkSuPW+qvpd7jFRHm7dLxOjUk1EHACJ/hxLY8phGJ0YhYHZo7jil7Qdg==";
  };
  "mkdirp@1.0.4" = fetchurl {
    url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
    hash = "sha512-vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
  };
  "mlly@1.8.0" = fetchurl {
    url = "https://registry.npmjs.org/mlly/-/mlly-1.8.0.tgz";
    hash = "sha512-l8D9ODSRWLe2KHJSifWGwBqpTZXIXTeo8mlKjY+E2HAakaTeNpqAyBZ8GSqLzHgw4XmHmC8whvpjJNMbFZN7/g==";
  };
  "neo-async@2.6.2" = fetchurl {
    url = "https://registry.npmjs.org/neo-async/-/neo-async-2.6.2.tgz";
    hash = "sha512-Yd3UES5mWCSqR+qNT93S3UoYUkqAZ9lLg8a7g9rimsWmYGK8cVToA4/sF3RrshdyV3sAGMXVUmpMYOw+dLpOuw==";
  };
  "node-fetch-native@1.6.7" = fetchurl {
    url = "https://registry.npmjs.org/node-fetch-native/-/node-fetch-native-1.6.7.tgz";
    hash = "sha512-g9yhqoedzIUm0nTnTqAQvueMPVOuIY16bqgAJJC8XOOubYFNwz6IER9qs0Gq2Xd0+CecCKFjtdDTMA4u4xG06Q==";
  };
  "nypm@0.5.4" = fetchurl {
    url = "https://registry.npmjs.org/nypm/-/nypm-0.5.4.tgz";
    hash = "sha512-X0SNNrZiGU8/e/zAB7sCTtdxWTMSIO73q+xuKgglm2Yvzwlo8UoC5FNySQFCvl84uPaeADkqHUZUkWy4aH4xOA==";
  };
  "ohash@1.1.6" = fetchurl {
    url = "https://registry.npmjs.org/ohash/-/ohash-1.1.6.tgz";
    hash = "sha512-TBu7PtV8YkAZn0tSxobKY2n2aAQva936lhRrj6957aDaCf9IEtqsKbgMzXE/F/sjqYOwmrukeORHNLe5glk7Cg==";
  };
  "open@10.1.2" = fetchurl {
    url = "https://registry.npmjs.org/open/-/open-10.1.2.tgz";
    hash = "sha512-cxN6aIDPz6rm8hbebcP7vrQNhvRcveZoJU72Y7vskh4oIm+BZwBECnx5nTmrlres1Qapvx27Qo1Auukpf8PKXw==";
  };
  "pathe@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/pathe/-/pathe-1.1.2.tgz";
    hash = "sha512-whLdWMYL2TwI08hn8/ZqAbrVemu0LNaNNJZX73O6qaIdCTfXutsLhMkjdENX0qhsQ9uIimo4/aQOmXkoon2nDQ==";
  };
  "pathe@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/pathe/-/pathe-2.0.3.tgz";
    hash = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
  };
  "perfect-debounce@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/perfect-debounce/-/perfect-debounce-1.0.0.tgz";
    hash = "sha512-xCy9V055GLEqoFaHoC1SoLIaLmWctgCUaBaWxDZ7/Zx4CTyX7cJQLJOok/orfjZAh9kEYpjJa4d0KcJmCbctZA==";
  };
  "pkg-types@1.3.1" = fetchurl {
    url = "https://registry.npmjs.org/pkg-types/-/pkg-types-1.3.1.tgz";
    hash = "sha512-/Jm5M4RvtBFVkKWRu2BLUTNP8/M2a+UwuAX+ae4770q1qVGtfjG+WTCupoZixokjmHiry8uI+dlY8KXYV5HVVQ==";
  };
  "rc9@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/rc9/-/rc9-2.1.2.tgz";
    hash = "sha512-btXCnMmRIBINM2LDZoEmOogIZU7Qe7zn4BpomSKZ/ykbLObuBdvG+mFq11DL6fjH1DRwHhrlgtYWG96bJiC7Cg==";
  };
  "readdirp@4.1.2" = fetchurl {
    url = "https://registry.npmjs.org/readdirp/-/readdirp-4.1.2.tgz";
    hash = "sha512-GDhwkLfywWL2s6vEjyhri+eXmfH6j1L7JE27WhqLeYzoh/A3DBaYGEj2H/HFZCn/kMfim73FXxEJTw06WtxQwg==";
  };
  "run-applescript@7.1.0" = fetchurl {
    url = "https://registry.npmjs.org/run-applescript/-/run-applescript-7.1.0.tgz";
    hash = "sha512-DPe5pVFaAsinSaV6QjQ6gdiedWDcRCbUuiQfQa2wmWV7+xC9bGulGI8+TdRmoFkAPaBXk8CrAbnlY2ISniJ47Q==";
  };
  "semver@7.7.2" = fetchurl {
    url = "https://registry.npmjs.org/semver/-/semver-7.7.2.tgz";
    hash = "sha512-RF0Fw+rO5AMf9MAyaRXI4AV0Ulj5lMHqVxxdSgiVbixSCXoEmmX/jk0CuJw4+3SqroYO9VoUh+HcuJivvtJemA==";
  };
  "source-map@0.6.1" = fetchurl {
    url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
    hash = "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
  };
  "tar@6.2.1" = fetchurl {
    url = "https://registry.npmjs.org/tar/-/tar-6.2.1.tgz";
    hash = "sha512-DZ4yORTwrbTj/7MZYq2w+/ZFdI6OZ/f9SFHR+71gIVUZhOQPHzVCLpvRnPgyaMpfWxxk/4ONva3GQSyNIKRv6A==";
  };
  "tiktoken@1.0.22" = fetchurl {
    url = "https://registry.npmjs.org/tiktoken/-/tiktoken-1.0.22.tgz";
    hash = "sha512-PKvy1rVF1RibfF3JlXBSP0Jrcw2uq3yXdgcEXtKTYn3QJ/cBRBHDnrJ5jHky+MENZ6DIPwNUGWpkVx+7joCpNA==";
  };
  "tinyexec@0.3.2" = fetchurl {
    url = "https://registry.npmjs.org/tinyexec/-/tinyexec-0.3.2.tgz";
    hash = "sha512-KQQR9yN7R5+OSwaK0XQoj22pwHoTlgYqmUscPYoknOoWCWfj/5/ABTMRi69FrKU5ffPVh5QcFikpWJI/P1ocHA==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "ufo@1.6.1" = fetchurl {
    url = "https://registry.npmjs.org/ufo/-/ufo-1.6.1.tgz";
    hash = "sha512-9a4/uxlTWJ4+a5i0ooc1rU7C7YOw3wT+UGqdeNNHWnOF9qcMBgLRS+4IYUqbczewFx4mLEig6gawh7X6mFlEkA==";
  };
  "uglify-js@3.19.3" = fetchurl {
    url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.19.3.tgz";
    hash = "sha512-v3Xu+yuwBXisp6QYTcH4UbH+xYJXqnq2m/LtQVWKWzYc1iehYnLixoQDN9FH6/j9/oybfd6W9Ghwkl8+UMKTKQ==";
  };
  "undici-types@5.26.5" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-5.26.5.tgz";
    hash = "sha512-JlCMO+ehdEIKqlFxk6IfVoAUVmgz7cU7zD/h9XZ0qzeosSHmUJVOzSQvvYSYWXkFXC+IfLKSIffhv0sVZup6pA==";
  };
  "undici-types@7.16.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.16.0.tgz";
    hash = "sha512-Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==";
  };
  "wordwrap@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
    hash = "sha512-gvVzJFlPycKc5dZN4yPkP8w7Dc37BtP1yczEneOb4uq34pXZcvrtRTmWV8W+Ume+XCxKgbjM+nevkyFPMybd4Q==";
  };
  "yallist@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
    hash = "sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
  };
  "zod@4.1.8" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.8.tgz";
    hash = "sha512-5R1P+WwQqmmMIEACyzSvo4JXHY5WiAFHRMg+zBZKgKS+Q1viRa0C1hmUKtHltoIFKtIdki3pRxkmpP74jnNYHQ==";
  };
}